const TASKS_ACTIONS = {
  GET_TASKS: {
    REQUEST: 'GET_TASKS_REQUEST',
    SUCCESS: 'GET_TASKS_SUCCESS',
    ERROR: 'GET_TASKS_ERROR',
  },
  ADD_TASK: {
    REQUEST: 'ADD_TASK_REQUEST',
    SAVE_LOCALLY: 'ADD_TASK_LOCALLY',
    SUCCESS: 'ADD_TASK_SUCCESS',
    ERROR: 'ADD_TASK_ERROR',
  },
  REMOVE_TASK: {
    REQUEST: 'REMOVE_TASK_REQUEST',
    SAVE_LOCALLY: 'REMOVE_TASK_LOCALLY',
    SUCCESS: 'REMOVE_TASK_SUCCESS',
    ERROR: 'REMOVE_TASK_ERROR',
  },
  EDIT_TASK: {
    REQUEST: 'EDIT_TASK_REQUEST',
    SAVE_LOCALLY: 'EDIT_TASK_LOCALLY',
    SUCCESS: 'EDIT_TASK_SUCCESS',
    ERROR: 'EDIT_TASK_ERROR',
  },
  SET_EDIT_TASK: 'SET_EDIT_TASK',
};
export default TASKS_ACTIONS;
